### ISSUE TITLE
同时选中【筛选条件】和【工厂信息】会导致二者的详情页重叠

### ISSUE THREAD

**Issue by ghost** [blacksnipebiu/MoreStatInfo#1]
mod - v1.3.4

菜鸡一枚，顶不住单文件2K行，放弃读代码了。作者你自己看看吧。
- - -
【筛选条件】和【工厂信息】，**此处重叠了**：![【筛选条件】和【工厂信息】](https://user-images.githubusercontent.com/67677979/230705267-9ce3462d-acf0-42a6-9c7f-06dacf37b2fb.jpg)
【工厂信息】：![【工厂信息】](https://user-images.githubusercontent.com/67677979/230705269-953bba4e-7f2d-4d56-97ff-8bc9d8e12131.jpg)
【筛选条件】：![【筛选条件】](https://user-images.githubusercontent.com/67677979/230705270-90013842-a7b8-43c6-a5a7-af925a85b0ff.jpg)

**Comment by blacksnipebiu** [comment]
已经修复好了
