### ISSUE TITLE
(v1.4.6+0.10.30.23430) 结构矩阵和引力矩阵的理论产量以及材料的需求产量计算有误

### ISSUE THREAD

**Issue by horeaper** [blacksnipebiu/MoreStatInfo#3]
如图所示：建造了8个矩阵研究站，黄糖的理论产量应该是60，实际显示为56
需求的材料所显示的需求产量也有误
![1](https://github.com/user-attachments/assets/1cee15b3-d7c8-44cc-b6d7-f9817f519238)
![2](https://github.com/user-attachments/assets/acaa318a-9d62-48ee-889d-90956ff1b5da)

同样的，建造了12个矩阵研究站，绿糖的理论产量应该是60，实际显示为24。材料需求同样是错的
![3](https://github.com/user-attachments/assets/f165bbd8-2760-4f76-878c-d625414e9edb)
![4](https://github.com/user-attachments/assets/7f472449-a0fc-4ac7-b3ba-20ad9e1fc01f)

实际运转起来后的实时产量和实时消耗是正确的。

游戏版本：0.10.30.23430
MOD版本：v1.4.6
通过r2modman 3.1.50启动游戏

**Comment by blacksnipebiu** [comment]
研究站被四舍五入误差了，但是绿糖12个一级研究站的基础理论产量不是2.5*8=20吗

**Comment by horeaper** [comment]
> 研究站被四舍五入误差了，但是绿糖12个一级研究站的基础理论产量不是2.5*8=20吗

绿糖24秒出2个，造12个研究站就是（60÷24×2）×12=60个/min

**Comment by blacksnipebiu** [comment]
哦，是我蠢了，那么将在1.4.8版本修复这个问题
