### ISSUE TITLE
(v1.4.8+0.10.30.23430) 内存泄漏导致一段时间后游戏体验明显下降

### ISSUE THREAD

**Issue by horeaper** [blacksnipebiu/MoreStatInfo#4]
该问题最早发现于1.4.6，之前版本可能也有，不过我是这几天才回归开坑的。

具体表现为，加载mod之后，正常游戏，观察到内存占用逐步上升，随后在放置/删除建筑的时候就开始卡顿，疑似系统在进行GC。
随着游戏时长增加（1小时以上），卡顿会越发明显，甚至严重到删掉建筑（特别是箱子）会卡1秒钟的程度。

利用BuildToolOpt将GC屏蔽掉之后，卡顿消失，但内存占用会快速增长。在我这次开的目前刚做完120糖的档，游戏接近3小时后内存占用会一路攀高到7.5GB，随后游戏会不定时卡顿，疑似在进行GC，并且卡顿时屏幕左上角会有一闪而过的红字，看不清内容。

重新加载、返回游戏主菜单重进都无效，只能退出游戏重进。
出现卡顿之后，哪怕我加载别的存档（比如一个地面上空空如也，我用来设计蓝图的沙盒档），一样会卡顿。
同样的，一直在这个沙盒档里面玩（有且仅有在同一个星球上设计蓝图），也会逐渐开始卡顿，但在卡顿变得无法接受前能多“坚持”一会儿。

其他信息：
更老的版本（黑雾更新之前的版本，上次玩戴森球都是22年10月的事了，存档的版本号是0.9.27，当时用的mod版本号忘了）玩的时候没有发现这个问题。
该档肝到了千糖，规模肯定足够大了，但我不记得有明显的卡顿，因此应该是没问题的。
（应该啊，毕竟该档我是玩了一半的时候才用上这个mod，人的记忆真的不可靠……）

**Comment by blacksnipebiu** [comment]
这个确实是之前写的太糙了，确实会有一大堆内存泄漏，我抽空优化一下

**Comment by blacksnipebiu** [comment]
1.4.9版本你再试试看呢

**Comment by horeaper** [comment]
好很多，在卡到不能玩之前能坚持三倍的时间了🤣

**Comment by blacksnipebiu** [comment]
所以还是会内存泄漏是吗

**Comment by horeaper** [comment]
是的，但是感觉泄露的量少了很多，卡顿的“增长”也变得平滑了不少，直到能明显感觉出卡顿之前，大约要两三个小时左右

**Comment by blacksnipebiu** [comment]
1.5.0版本你再试试呢

**Comment by horeaper** [comment]
刚开游戏就碰见了这个
![Untitled](https://github.com/user-attachments/assets/a2f9a5a6-db4b-4eab-8cdf-eceecc8e61e1)
还有数字的字体变得怪怪的……

**Comment by blacksnipebiu** [comment]
字体有什么问题，字体做成可变大小的了，所以跟之前不太一样

**Comment by horeaper** [comment]
没啥问题，就是跟过去不一样了。突然改变有点不习惯😅

**Comment by blacksnipebiu** [comment]
颜色没变，就是字体大小和粗体改了

**Comment by horeaper** [comment]
找到了IndexOutOfRangeException的重现方式：
进游戏后，直接打开界面，点击筛选条件，选中只看目标产物和依目标产物排序，然后点一个物品：
![Untitled](https://github.com/user-attachments/assets/61041245-2f64-401c-a007-72b53ea3bce3)

**Comment by blacksnipebiu** [comment]
好的，晚上1.5.1版本修

**Comment by horeaper** [comment]
就我玩的这一下午的体验来说，1.5.0的内存泄漏问题并没有比1.4.9有改善，仍然是在两到三个小时后内存占用飙升（5G以上），放置建筑/删除箱子时会逐渐开始卡顿且在两三个小时后到了无法接受的程度。
（我的档没有进一步扩张，仍然是120糖的规模，这段时间沉迷设计混线蓝图了😁）

**Comment by blacksnipebiu** [comment]
1.5.1版本更新了，又重构了一个函数，然后修复了你说的bug

**Comment by horeaper** [comment]
可惜的是，1.5.1的内存泄漏仍然是可观的。
为了再次对比几确认，我这次在保持其他mod继续开启的状态下，只关闭了本mod。拍建筑时候的流畅度有一个明显的提升。情况总结一下是这样：

开启的mod：除去AuxilaryFunction外，大的mod就只有一个BlueprintTweaks。剩下的就是AssemblerUI、DSPStationInfo、DSPAutoSorter、MoreReplication、ToggleGodMode这几个比较简单的mod。

开始游戏一个小时内拍建筑/拆箱子：
关闭本mod：非常流畅，是游戏正常的体验。
开启本mod：会有些微的卡顿，可感知但不影响体验。
此时内存占用都在3.5个G左右。

继续游戏约三个小时后拍建筑/拆箱子：
关闭本mod：会有些微的卡顿，可感知但不影响体验。内存占用4G。
开启本mod：有明显的卡顿，游戏画面左上角会出现提示lag的红字，非常影响体验。内存占用5.3G。

主要进行的操作是在一个空荡荡的沙盒档里设计并测试各种蓝图。设计好了后回主档拍下去，但不开启运作。
拍建筑时拍箱子/熔炉/制造器这些有内部储存空间的东西，卡顿明显。拍传送带则卡顿会小一些。
拆建筑时只有拆箱子的时候会卡顿，且卡顿非常明显，远大于拍建筑。拆别的建筑则不卡。（拆物流塔除外，不过拆这玩意儿就算只玩本体不打mod都会卡顿一下所以应该没关联）

对比1.5.0，确实好了一丢丢，但不明显，可能也就我这种沙盒蓝图狂热症患者能体会出区别了🤣

情况比起1.4.8时候已经好了很多，那时候一个小时游戏时间就已经开始出lag红字了。要是坚持着玩到两三个小时，拆个箱子能卡一两秒。现在没那么夸张了，玩两三个小时的卡顿感觉差不多就是之前一个小时的感觉。

**Comment by blacksnipebiu** [comment]
又更新了一版1.5.2

**Comment by horeaper** [comment]
“筛选条件”进行过滤的功能完全失效了
并且当内容不满的时候会有布局错误
![Untitled](https://github.com/user-attachments/assets/9c40591c-c99d-4e6a-927b-62532d00876a)

**Comment by blacksnipebiu** [comment]
1.5.3修了

**Comment by horeaper** [comment]
最大的内存占用有所下降（现在最大到5G），但是卡顿仍然有。而且这次就算我什么都不干，站在原地挂机产白糖，经过半个小时左右进行拍箱子/拆箱子，就已经能感觉出卡顿了，两个小时后卡顿明显。
当然箱子是问题最严重的。拍其他建筑有卡顿（主要是熔炉和制造台），但会比箱子要低很多。
不过这次即使是拆箱子也没在屏幕左上角看见lag红字。
（这次测试时间不是很足，国庆挺多事情的>_<）

**Comment by blacksnipebiu** [comment]
你能帮我测试一下开始就点停止刷新，然后再也不打开统计面板会不会卡吗

**Comment by horeaper** [comment]
好，我现在去～～

**Comment by horeaper** [comment]
> 你能帮我测试一下开始就点停止刷新，然后再也不打开统计面板会不会卡吗

两个小时过去了，卡出lag红字了，内存占用也上到5G了=_=

**Comment by blacksnipebiu** [comment]
纯挂后台也卡啊

**Comment by blacksnipebiu** [comment]
1.5.4版本应该是可以了，我根据你提供的条件，再自己测试了剩下的部分，找到了应该是多线程导致的内存泄漏gc无法回收，深层原因还没搞懂，你再帮我看看你那边还会不会泄露

**Comment by horeaper** [comment]
成了！！两个小时下来，卡顿和内存占用都和不开mod时候几乎一致！没有用停止刷新，是正常的在玩的。
撒花撒花✿✿ヽ(°▽°)ノ✿

**Comment by blacksnipebiu** [comment]
真实没想到这句代码会是元凶
`
ThreadPool.QueueUserWorkItem(_ =>
{
    while (true)
    {
        OneSecondElapsed = true;
        Thread.Sleep(1000);
    }
});
`

**Comment by horeaper** [comment]
现在这个版本有一点不一样，就是以前开一个新档之后，面板里不是没有任何东西显示么，这时候拍个制造器或者熔炉下去，选择一个配方，就能直接在面板里看到物品以及它的理论产量和需求产量这些了。开新档的时候非常方便。现在则是变得和自带的分析面板一样，需要至少把物品获取一遍才会显示出来。
是个小问题，现在这样只是有点麻烦。不过以前这个“特性”也算是这个mod的特色了。能不能改回原来的模式？会麻烦吗？

**Comment by blacksnipebiu** [comment]
是之前检查内存泄漏时做的设计，确实是可以改回来

**Comment by horeaper** [comment]
非常好用，1.5.5这个版本已经很完美了🤩
