### ISSUE TITLE
(v1.4.8+0.10.30.23430) 只启用MoreStatInfo而不启用Auxilaryfunction时，面板的渲染会出问题

### ISSUE THREAD

**Issue by horeaper** [blacksnipebiu/MoreStatInfo#5]
如图：
![Untitled](https://github.com/user-attachments/assets/55457039-a759-4a2c-bc4e-6471280585df)

测试隔壁那个内存泄漏问题的时候发现的，我是一个一个mod挨个关闭时意外测出来这个奇怪bug的……
只启用MoreStatInfo，就会这样。然而再启用Auxilaryfunction，就好了。

mod管理器是r2modman 3.1.50

**Comment by blacksnipebiu** [comment]
ctrl+鼠标滚轮或者方向键上下可以自由调整

**Comment by horeaper** [comment]
ctrl+滚轮了一下确实好了，不过关掉再重进游戏后就又坏掉了，还要再次ctrl+滚轮
